export const GET_REGION_DATA = "GET_REGION_DATA";
export const POST_REGION_DATA = "POST_REGION_DATA";
export const GET_DISTRICT_DATA = "GET_DISTRICT_DATA";
export const GET_OFFICE_DATA = "GET_OFFICE_DATA";
export const GET_IDTYPE_DATA = "GET_IDTYPE_DATA";
export const GET_COMMUNICATIONTYPE_DATA = "GET_COMMUNICATIONTYPE_DATA";
export const GET_SUBCATEGORY_DATA = "GET_SUBCATEGORY_DATA";
export const GET_LOCATIONOFINCIDENT_DATA = "GET_LOCATIONOFINCIDENT_DATA";
